# Generated by Django 5.0.6 on 2024-06-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0003_question_personanswer_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='question',
            name='complexity_level',
            field=models.CharField(choices=[('1', 'easy'), ('2', 'medium'), ('3', 'hard')], default='1', max_length=200),
        ),
        migrations.AlterField(
            model_name='exam',
            name='topic',
            field=models.CharField(choices=[('KET', 'keliu eimo taisykles'), ('animals', 'gyvunai'), ('flowers', 'geles')], max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=200),
        ),
    ]
